MAHOUT-1590 Upgraded h2o from 0.1.16 to 0.1.25; 0.1.16 had a bug fixe din 0.1.19, bug which was causing our tests to fail with NoClassDefFoundError for org.apache.hadoop.fs.s3.S3Exception class