[EXPIRMENTAL BRANCH] gpuRWRW was failing with a missing allocator when directed from:
java.lang.UnsatisfiedLinkError: org.apache.mahout.viennacl.vcl.javacpp.Context.allocate(I)V
at org.apache.mahout.viennacl.vcl.javacpp.Context.allocate(Native Method)
at org.apache.mahout.viennacl.vcl.javacpp.Context.<init>(Context.scala:33)
at org.apache.mahout.viennacl.vcl.GPUMMul$.org4600gpuRWRW(GPUMMul.scala:146)
at org.apache.mahout.viennacl.vcl.GPUMMul$.org4600jvmCWRW(GPUMMul.scala:174)
at org.apache.mahout.viennacl.vcl.GPUMMul4600anonfun6.apply(GPUMMul.scala:79)

revert to jvm for now just to get some passing tests